#pragma once

/* The way how "handedness" is decided (which half is which),
see https://docs.qmk.fm/#/feature_split_keyboard?id=setting-handedness
for more options.
*/
#define RGB_DI_PIN D3
#define RGBLED_NUM 8
#define RGB_SPLIT { 4, 4 }
#define RGBLIGHT_SPLIT
#define RGBLIGHT_SLEEP
#define WS2812_BYTE_ORDER WS2812_BYTE_ORDER_RGB
#define WS2812_TRST_US WS2812_TIMING
#define WS2812_DI_PIN RGB_DI_PIN
#define NO_ACTION_ONESHOT
#define NO_ACTION_TAPPING
#define SPLIT_WPM_ENABLE 
 
 #undef ENABLE_RGB_MATRIX_ALPHAS_MODS
 #undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
 #undef ENABLE_RGB_MATRIX_BREATHING
 #undef ENABLE_RGB_MATRIX_CYCLE_ALL
 #undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
 #undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
 #undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
 #undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
 #undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
 #undef ENABLE_RGB_MATRIX_DUAL_BEACON
 #undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
 #undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
 #undef ENABLE_RGB_MATRIX_RAINDROPS
 #undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
 #undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
 #undef ENABLE_RGB_MATRIX_DIGITAL_RAIN
 #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
 #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
 #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
 #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
 #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
 #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
 #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
 #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
 #undef ENABLE_RGB_MATRIX_SPLASH
 #undef ENABLE_RGB_MATRIX_MULTISPLASH
 #undef ENABLE_RGB_MATRIX_SOLID_SPLASH
 #undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
